# Generated by Django 3.0.5 on 2020-04-06 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_creation_date', models.DateTimeField(auto_now_add=True)),
                ('farmer_name', models.CharField(max_length=100)),
                ('farmer_siret_number', models.PositiveIntegerField()),
                ('farmer_address', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['farmer_creation_date'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_creation_date', models.DateTimeField(auto_now_add=True)),
                ('product_name', models.CharField(max_length=100)),
                ('product_unit', models.PositiveIntegerField()),
                ('international_food_code', models.TextField(max_length=15)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
                ('producers', models.ManyToManyField(to='snippets.Farmer')),
            ],
            options={
                'ordering': ['product_creation_date'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_creation_date', models.DateTimeField(auto_now_add=True)),
                ('certificate_name', models.CharField(max_length=100)),
                ('certificate_type', models.CharField(choices=[('BIOLOGIQUE', 'Biologique'), ('SANS_OGM', 'Sans OGM'), ('ORIGINE', 'Origine')], default='ORIGINE', max_length=10)),
                ('certified_farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snippets.Farmer')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['certificate_creation_date'],
            },
        ),
    ]
